/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiRule } from "./apirule";
import { Expose, Type } from "class-transformer";

export class AddRuleInput extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "rule" })
  @Type(() => ApiRule)
  rule?: ApiRule;
}
