/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ModelsRule } from "./modelsrule";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ApiAllRulesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: string;

  @SpeakeasyMetadata({ elemType: ModelsRule })
  @Expose({ name: "rules" })
  @Type(() => ModelsRule)
  rules?: ModelsRule[];
}
