/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiRule } from "./apirule";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ApiAllRulesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: string;

  @SpeakeasyMetadata({ elemType: ApiRule })
  @Expose({ name: "rules" })
  @Type(() => ApiRule)
  rules?: ApiRule[];
}
