/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ApiEvaluationResult extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "Value" })
  value?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "actionTargetType" })
  actionTargetType?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "targetID" })
  targetID?: string;
}
