/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ModelsEvaluationResult } from "./modelsevaluationresult";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ApiEvaluateRulesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: ModelsEvaluationResult })
  @Expose({ name: "results" })
  @Type(() => ModelsEvaluationResult)
  results?: ModelsEvaluationResult[];
}
