/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ModelsRule } from "./modelsrule";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ApiReplaceRuleResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "rule" })
  @Type(() => ModelsRule)
  rule?: ModelsRule;
}
