/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ConditionTypeEnum {
  E = "e",
  Hv = "hv",
  Eq = "eq",
  Neq = "neq",
  Px = "px",
  Npx = "npx",
  Sx = "sx",
  Nsx = "nsx",
  In = "in",
  Nin = "nin",
  Rgx = "rgx",
  Nrgx = "nrgx",
}
