/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ModelsRule } from "./modelsrule";
import { Expose, Type } from "class-transformer";

export class EvaluateRulesInput extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "object" })
  object: Record<string, any>;

  @SpeakeasyMetadata()
  @Expose({ name: "overrideCode" })
  overrideCode?: string;

  @SpeakeasyMetadata({ elemType: ModelsRule })
  @Expose({ name: "overrideRules" })
  @Type(() => ModelsRule)
  overrideRules?: ModelsRule[];
}
