/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApiRule } from "./apirule";
import { Expose, Type } from "class-transformer";

export class EvaluateRulesInput extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "object" })
  object: Record<string, any>;

  @SpeakeasyMetadata()
  @Expose({ name: "overrideCode" })
  overrideCode?: string;

  @SpeakeasyMetadata({ elemType: ApiRule })
  @Expose({ name: "overrideRules" })
  @Type(() => ApiRule)
  overrideRules?: ApiRule[];
}
