/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import industries.dot.brease.utils.SpeakeasyMetadata;

public class AddRuleRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public industries.dot.brease.models.shared.AddRuleInput addRuleInput;

    public AddRuleRequest withAddRuleInput(industries.dot.brease.models.shared.AddRuleInput addRuleInput) {
        this.addRuleInput = addRuleInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contextID")
    public String contextID;

    public AddRuleRequest withContextID(String contextID) {
        this.contextID = contextID;
        return this;
    }
    
    public AddRuleRequest(@JsonProperty("contextID") String contextID) {
        this.contextID = contextID;
  }
}
