/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import industries.dot.brease.utils.SpeakeasyMetadata;

public class EvaluateRulesRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public industries.dot.brease.models.shared.EvaluateRulesInput evaluateRulesInput;
    public EvaluateRulesRequest withEvaluateRulesInput(industries.dot.brease.models.shared.EvaluateRulesInput evaluateRulesInput) {
        this.evaluateRulesInput = evaluateRulesInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contextID")
    public String contextID;
    public EvaluateRulesRequest withContextID(String contextID) {
        this.contextID = contextID;
        return this;
    }
    

    public EvaluateRulesRequest(@JsonProperty("contextID") String contextID) {
    this.contextID = contextID;
  }
}
