/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import industries.dot.brease.utils.SpeakeasyMetadata;

public class GetAllRulesRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contextID")
    public String contextID;
    public GetAllRulesRequest withContextID(String contextID) {
        this.contextID = contextID;
        return this;
    }
    
    public GetAllRulesRequest(@JsonProperty("contextID") String contextID) {
        this.contextID = contextID;
  }
}
