/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.operations;

import industries.dot.brease.utils.SpeakeasyMetadata;

public class RemoveRuleRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contextID")
    public String contextID;
    public RemoveRuleRequest withContextID(String contextID) {
        this.contextID = contextID;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;
    public RemoveRuleRequest withId(String id) {
        this.id = id;
        return this;
    }
    
}
