/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.operations;

import java.net.http.HttpResponse;

public class ReplaceRuleResponse {
    /**
     * OK
     */
    
    public industries.dot.brease.models.shared.ApiReplaceRuleResponse apiReplaceRuleResponse;
    public ReplaceRuleResponse withApiReplaceRuleResponse(industries.dot.brease.models.shared.ApiReplaceRuleResponse apiReplaceRuleResponse) {
        this.apiReplaceRuleResponse = apiReplaceRuleResponse;
        return this;
    }
    
    
    public String contentType;
    public ReplaceRuleResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ReplaceRuleResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ReplaceRuleResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
