/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import industries.dot.brease.utils.SpeakeasyMetadata;

public class ReplaceRuleRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public industries.dot.brease.models.shared.ReplaceRuleInput replaceRuleInput;
    public ReplaceRuleRequest withReplaceRuleInput(industries.dot.brease.models.shared.ReplaceRuleInput replaceRuleInput) {
        this.replaceRuleInput = replaceRuleInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contextID")
    public String contextID;
    public ReplaceRuleRequest withContextID(String contextID) {
        this.contextID = contextID;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;
    public ReplaceRuleRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public ReplaceRuleRequest(@JsonProperty("contextID") String contextID, @JsonProperty("id") String id) {
        this.contextID = contextID;
        this.id = id;
  }
}
