// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIAllRulesResponse - OK
type APIAllRulesResponse struct {
	Code  *string   `json:"code,omitempty"`
	Rules []APIRule `json:"rules,omitempty"`
}
