// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIEvaluateRulesResponse - OK
type APIEvaluateRulesResponse struct {
	Results []APIEvaluationResult `json:"results,omitempty"`
}
