// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIReplaceRuleResponse - OK
type APIReplaceRuleResponse struct {
	Rule *ModelsRule `json:"rule,omitempty"`
}
