// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIRule struct {
	Action      string                 `json:"action"`
	Description *string                `json:"description,omitempty"`
	Expression  map[string]interface{} `json:"expression"`
	ID          string                 `json:"id"`
	Target      string                 `json:"target"`
	TargetType  string                 `json:"targetType"`
	TargetValue *string                `json:"targetValue,omitempty"`
}
