// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Condition struct {
	Base      *ConditionBase      `json:"base,omitempty"`
	Parameter *ConditionParameter `json:"parameter,omitempty"`
	Type      *ConditionType      `json:"type,omitempty"`
}
