// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EvaluateRulesInput struct {
	Object        map[string]interface{} `json:"object"`
	OverrideCode  *string                `json:"overrideCode,omitempty"`
	OverrideRules []APIRule              `json:"overrideRules,omitempty"`
}
