// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsTarget struct {
	Target      string  `json:"target"`
	TargetValue *string `json:"targetValue,omitempty"`
	Type        string  `json:"type"`
}
