// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsEvaluationResult struct {
	Value            *string `json:"Value,omitempty"`
	Action           *string `json:"action,omitempty"`
	ActionTargetType *string `json:"actionTargetType,omitempty"`
	TargetID         *string `json:"targetID,omitempty"`
}
