// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsRule struct {
	Action      string       `json:"action"`
	Description *string      `json:"description,omitempty"`
	Expression  Expression   `json:"expression"`
	ID          string       `json:"id"`
	Target      ModelsTarget `json:"target"`
}
