/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ApiAllRulesResponse - OK
 */
public class ApiAllRulesResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    public String code;

    public ApiAllRulesResponse withCode(String code) {
        this.code = code;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rules")
    public ModelsRule[] rules;

    public ApiAllRulesResponse withRules(ModelsRule[] rules) {
        this.rules = rules;
        return this;
    }
    
    public ApiAllRulesResponse(){}
}
