/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ApiEvaluationResult {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("Value")
    public String value;
    public ApiEvaluationResult withValue(String value) {
        this.value = value;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    public String action;
    public ApiEvaluationResult withAction(String action) {
        this.action = action;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("actionTargetType")
    public String actionTargetType;
    public ApiEvaluationResult withActionTargetType(String actionTargetType) {
        this.actionTargetType = actionTargetType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("targetID")
    public String targetID;
    public ApiEvaluationResult withTargetID(String targetID) {
        this.targetID = targetID;
        return this;
    }
    
}
