/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ApiRule {
    @JsonProperty("action")
    public String action;
    public ApiRule withAction(String action) {
        this.action = action;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;
    public ApiRule withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("expression")
    public java.util.Map<String, Object> expression;
    public ApiRule withExpression(java.util.Map<String, Object> expression) {
        this.expression = expression;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public ApiRule withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("target")
    public String target;
    public ApiRule withTarget(String target) {
        this.target = target;
        return this;
    }
    
    @JsonProperty("targetType")
    public String targetType;
    public ApiRule withTargetType(String targetType) {
        this.targetType = targetType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("targetValue")
    public String targetValue;
    public ApiRule withTargetValue(String targetValue) {
        this.targetValue = targetValue;
        return this;
    }
    
}
