/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Condition {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("base")
    public Object base;
    public Condition withBase(Object base) {
        this.base = base;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parameter")
    public Object parameter;
    public Condition withParameter(Object parameter) {
        this.parameter = parameter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public ConditionTypeEnum type;
    public Condition withType(ConditionTypeEnum type) {
        this.type = type;
        return this;
    }
    
}
