/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ConditionTypeEnum {
    E("e"),
    HV("hv"),
    EQ("eq"),
    NEQ("neq"),
    PX("px"),
    NPX("npx"),
    SX("sx"),
    NSX("nsx"),
    IN("in"),
    NIN("nin"),
    RGX("rgx"),
    NRGX("nrgx");

    @JsonValue
    public final String value;

    private ConditionTypeEnum(String value) {
        this.value = value;
    }
}
