/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ConditionBase2 {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ref")
    public ConditionBaseRef ref;
    public ConditionBase2 withRef(ConditionBaseRef ref) {
        this.ref = ref;
        return this;
    }
    
}
