/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class EvaluateRulesInput {
    @JsonProperty("object")
    public java.util.Map<String, Object> object;
    public EvaluateRulesInput withObject(java.util.Map<String, Object> object) {
        this.object = object;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("overrideCode")
    public String overrideCode;
    public EvaluateRulesInput withOverrideCode(String overrideCode) {
        this.overrideCode = overrideCode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("overrideRules")
    public ApiRule[] overrideRules;
    public EvaluateRulesInput withOverrideRules(ApiRule[] overrideRules) {
        this.overrideRules = overrideRules;
        return this;
    }
    
}
