/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ExpressionArray {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expression")
    public Object[] expression;
    public ExpressionArray withExpression(Object[] expression) {
        this.expression = expression;
        return this;
    }
    
}
