/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ModelsTarget {
    @JsonProperty("target")
    public String target;
    public ModelsTarget withTarget(String target) {
        this.target = target;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("targetValue")
    public String targetValue;
    public ModelsTarget withTargetValue(String targetValue) {
        this.targetValue = targetValue;
        return this;
    }
    
    @JsonProperty("type")
    public String type;
    public ModelsTarget withType(String type) {
        this.type = type;
        return this;
    }
    
    public ModelsTarget(@JsonProperty("target") String target, @JsonProperty("type") String type) {
        this.target = target;
        this.type = type;
  }
}
