/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ModelsRuleExpression1 {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("and")
    public ExpressionArray and;
    public ModelsRuleExpression1 withAnd(ExpressionArray and) {
        this.and = and;
        return this;
    }
    
    public ModelsRuleExpression1(){}
}
