/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ModelsRule {
    @JsonProperty("action")
    public String action;
    public ModelsRule withAction(String action) {
        this.action = action;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;
    public ModelsRule withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("expression")
    public Object expression;
    public ModelsRule withExpression(Object expression) {
        this.expression = expression;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public ModelsRule withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("target")
    public ModelsTarget target;
    public ModelsRule withTarget(ModelsTarget target) {
        this.target = target;
        return this;
    }
    

    public ModelsRule(@JsonProperty("action") String action, @JsonProperty("expression") Object expression, @JsonProperty("id") String id, @JsonProperty("target") ModelsTarget target) {
    this.action = action;
this.expression = expression;
this.id = id;
this.target = target;
  }
}
