/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package industries.dot.brease.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ReplaceRuleInput {
    @JsonProperty("rule")
    public ModelsRule rule;
    public ReplaceRuleInput withRule(ModelsRule rule) {
        this.rule = rule;
        return this;
    }
    

    public ReplaceRuleInput(@JsonProperty("rule") ModelsRule rule) {
    this.rule = rule;
  }
}
