// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"brease/pkg/models/shared"
	"net/http"
)

type AddRuleSecurity struct {
	APIToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type AddRuleRequest struct {
	AddRuleInput *shared.AddRuleInput `request:"mediaType=application/json"`
	ContextID    string               `pathParam:"style=simple,explode=false,name=contextID"`
}

type AddRuleResponse struct {
	// OK
	APIAddRuleResponse *shared.APIAddRuleResponse
	ContentType        string
	StatusCode         int
	RawResponse        *http.Response
}
