// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"brease/pkg/models/shared"
	"net/http"
)

type EvaluateRulesSecurity struct {
	APIToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type EvaluateRulesRequest struct {
	EvaluateRulesInput *shared.EvaluateRulesInput `request:"mediaType=application/json"`
	ContextID          string                     `pathParam:"style=simple,explode=false,name=contextID"`
}

type EvaluateRulesResponse struct {
	// OK
	APIEvaluateRulesResponse *shared.APIEvaluateRulesResponse
	ContentType              string
	StatusCode               int
	RawResponse              *http.Response
}
