// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"brease/pkg/models/shared"
	"net/http"
)

type GetAllRulesSecurity struct {
	APIToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetAllRulesRequest struct {
	ContextID string `pathParam:"style=simple,explode=false,name=contextID"`
}

type GetAllRulesResponse struct {
	// OK
	APIAllRulesResponse *shared.APIAllRulesResponse
	ContentType         string
	StatusCode          int
	RawResponse         *http.Response
}
