// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemoveRuleSecurity struct {
	APIToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type RemoveRuleRequest struct {
	ContextID string `pathParam:"style=simple,explode=false,name=contextID"`
	ID        string `pathParam:"style=simple,explode=false,name=id"`
}

type RemoveRuleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
