"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ConditionType(str, Enum):
    E = 'e'
    HV = 'hv'
    EQ = 'eq'
    NEQ = 'neq'
    PX = 'px'
    NPX = 'npx'
    SX = 'sx'
    NSX = 'nsx'
    IN = 'in'
    NIN = 'nin'
    RGX = 'rgx'
    NRGX = 'nrgx'
