"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import apievaluaterulesresponse as shared_apievaluaterulesresponse
from ..shared import evaluaterulesinput as shared_evaluaterulesinput
from typing import Optional


@dataclasses.dataclass
class EvaluateRulesSecurity:
    
    api_token: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class EvaluateRulesRequest:
    
    context_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'contextID', 'style': 'simple', 'explode': False }})
    evaluate_rules_input: Optional[shared_evaluaterulesinput.EvaluateRulesInput] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    

@dataclasses.dataclass
class EvaluateRulesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_evaluate_rules_response: Optional[shared_apievaluaterulesresponse.APIEvaluateRulesResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    