"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import apiallrulesresponse as shared_apiallrulesresponse
from typing import Optional


@dataclasses.dataclass
class GetAllRulesSecurity:
    
    api_token: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class GetAllRulesRequest:
    
    context_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'contextID', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetAllRulesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_all_rules_response: Optional[shared_apiallrulesresponse.APIAllRulesResponse] = dataclasses.field(default=None)
    r"""OK"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    