name: Generate
permissions:
  checks: write
  contents: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force the generation of the SDKs
        type: boolean
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      force: ${{ github.event.inputs.force }}
      languages: |
        - java: java-client-sdk
        - python: python-client-sdk
        - typescript: typescript-client-sdk
        - go: go-client-sdk
      openapi_doc_auth_header: x-api-key
      openapi_doc_location: https://prod.speakeasyapi.dev/v1/apis/brease/version/0.1/schema/download
      publish_python: true
      publish_typescript: true
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      openapi_doc_auth_token: ${{ secrets.SPEAKEASY_API_KEY }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_PROD_API_KEY }}
